
services:
  hive4:
    image: apache/hive:4.0.0
    container_name: hive4
    environment:
      - SERVICE_NAME=hiveserver2      
    ports:
      - "10000:10000"
      - "10002:10002"
    volumes:
      - ./hive4_data:/opt/hive/host_data/data_db

volumes:
  hive4_data:
    driver: local
    driver_opts:
      type: none
      o:
        bind
      device: /hive4_data
